### ISSUE TITLE
Run app independently?

### ISSUE THREAD

**Issue by jnixon2** [jualoppaz/single-spa-angular-app#1]
Is it possible to run this app independently? when i run this with ng serve i get a blank screen?

Thanks

**Comment by jualoppaz** [comment]
Hi @jnixon2 ! 

With the current config in this project there is no way of running this angular app independently.

Notice that in the angular.json file is set the custom webpack builder of single-spa for build and serve the app, which points to main.single-spa.ts file instead of default main.ts file.

The reason you see a blank page is due to you are exporting the required single-spa methods (bootstrap, mount and unmount) but there is no single-spa root application catching them for init the lifecycle.

If you want to run this project on its own you should though about a way of keeping default angular.json config for that case in order to use main.ts file and not the current main.single-spa.ts file. A valid content for the angular.json file could be the previous one:

https://github.com/jualoppaz/single-spa-angular-app/blob/75308acad1380602467e8eb245b153d2fdb6e334/angular.json#L18-L34

https://github.com/jualoppaz/single-spa-angular-app/blob/75308acad1380602467e8eb245b153d2fdb6e334/angular.json#L67-L77


As it seems that there is no possibility of having more than one angular.json file, another strategy could be add new schematics for your use case. Reading this [https://medium.com/@tomastrajan/total-guide-to-custom-angular-schematics-5c50cf90cdb4](article) you will understand what I mean.

Hope this information be useful.
